Repository jenkinsci/docker-fixtures, pull requests merged in 2022-09, with the labels that each got.

#41 [SECURITY] Fix Temporary Directory Hijacking or Information Disclosure Vulnerability
  src/main/java/org/jenkinsci/test/acceptance/docker/Docker.java
Labels: bug

#43 Updates; support Java 17
  Jenkinsfile
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/docker/DockerImage.java
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/SshdContainer.java
  src/test/java/org/jenkinsci/test/acceptance/docker/DockerImageTest.java
Labels: enhancement

#44 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/extensions.xml
  .mvn/maven.config
  Jenkinsfile
  pom.xml
Labels: developer

#45 Restore ability to use library from Java 8-based clients
  pom.xml
Labels: bug
